### ISSUE TITLE
Bug: If I enter spaces for the Title and Author the server crashes.

### ISSUE THREAD

**Issue by td-extreme** [Naomi-Dennis/books-draft#1]
TypeError: /home/tyler/Temp/code_review/books-draft/app/views/layout.ejs:12
    10|   </head>
    11|   <body>
 >> 12|   <%- include(`${view_path}` + `.ejs`) %>
    13| 
    14|   <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
    15|   </body>

/home/tyler/Temp/code_review/books-draft/app/views/google_books/index.ejs:53
    51| 	    <li>Written By:</li>
    52| 	    <ul>
 >> 53| 		<% for(let a = 0; a < searched_books[i].volumeInfo.authors.length; a++){ %> 
    54| 		  <li><%= searched_books[i].volumeInfo.authors[a] %> </li>
    55| 		<% } %> 
    56| 		</ul>

Cannot read property 'length' of undefined
    at eval (eval at compile (/home/tyler/Temp/code_review/books-draft/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:30:64)
    at returnedFn (/home/tyler/Temp/code_review/books-draft/node_modules/ejs/lib/ejs.js:668:17)
    at include (/home/tyler/Temp/code_review/books-draft/node_modules/ejs/lib/ejs.js:666:39)
    at eval (eval at compile (/home/tyler/Temp/code_review/books-draft/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:11:17)
    at returnedFn (/home/tyler/Temp/code_review/books-draft/node_modules/ejs/lib/ejs.js:668:17)
    at tryHandleCache (/home/tyler/Temp/code_review/books-draft/node_modules/ejs/lib/ejs.js:254:36)
    at View.exports.renderFile [as engine] (/home/tyler/Temp/code_review/books-draft/node_modules/ejs/lib/ejs.js:485:10)
    at View.render (/home/tyler/Temp/code_review/books-draft/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/tyler/Temp/code_review/books-draft/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/tyler/Temp/code_review/books-draft/node_modules/express/lib/application.js:592:3)

**Comment by Naomi-Dennis** [comment]
Thanks for catching that! Please see the thread below for a solution! 

#2
