### ISSUE TITLE
Bug:  Cannot read property 'smallThumbnail' of undefined

### ISSUE THREAD

**Issue by td-extreme** [Naomi-Dennis/books-draft#2]
Search parameters
Title : "oh the places you'll go"
Author: "seuss"

error:

TypeError: /home/tyler/Temp/code_review/books-draft/app/views/layout.ejs:12
    10|   </head>
    11|   <body>
 >> 12|   <%- include(`${view_path}` + `.ejs`) %>
    13| 
    14|   <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
    15|   </body>

/home/tyler/Temp/code_review/books-draft/app/views/google_books/index.ejs:49
    47| 		<h3 style="text-align:center"><%= searched_books[i].volumeInfo.title %></h3>
    48| 
 >> 49| 	    <img id='book-cover' src="<%= searched_books[i].volumeInfo.imageLinks.smallThumbnail %>" width="100px" height="150px" alt="Cover of <%= searched_books[i].volumeInfo.title %>" title="<%= searched_books[i].volumeInfo.title %>">
    50| 	    <ul>
    51| 	    <li>Written By:</li>
    52| 	    <ul>

Cannot read property 'smallThumbnail' of undefined
    at eval (eval at compile (/home/tyler/Temp/code_review/books-draft/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:23:66)
    at returnedFn (/home/tyler/Temp/code_review/books-draft/node_modules/ejs/lib/ejs.js:668:17)
    at include (/home/tyler/Temp/code_review/books-draft/node_modules/ejs/lib/ejs.js:666:39)
    at eval (eval at compile (/home/tyler/Temp/code_review/books-draft/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:11:17)
    at returnedFn (/home/tyler/Temp/code_review/books-draft/node_modules/ejs/lib/ejs.js:668:17)
    at tryHandleCache (/home/tyler/Temp/code_review/books-draft/node_modules/ejs/lib/ejs.js:254:36)
    at View.exports.renderFile [as engine] (/home/tyler/Temp/code_review/books-draft/node_modules/ejs/lib/ejs.js:485:10)
    at View.render (/home/tyler/Temp/code_review/books-draft/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/tyler/Temp/code_review/books-draft/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/tyler/Temp/code_review/books-draft/node_modules/express/lib/application.js:592:3)

**Comment by Naomi-Dennis** [comment]
Thanks for catching that! A fix has been applied.

For more info, see the commit below: 

[**Commit**](https://github.com/Naomi-Dennis/books-draft/commit/0e4b283d1204837011988bef3947d48aa1782730)
